var path = require('path');
var express = require('express');
import healthcheck from './healthcheck';
import upload  from './upload';
var app = express();
var PORT = 8000;
app.use(express.static(__dirname + '/dist'));
app.get('/_healthcheck', healthcheck);
app.get('/upload', upload);
console.log('Listening on port: ' + PORT);
app.listen(PORT);
