export const ADD_CART_ITEM = 'ADD_CART_ITEM';

export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_COMPLETE = 'GET_PRODUCTS_COMPLETE';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
